---

- name: install required packages
  apt:
    name: "{{ item }}"
  with_items: pg_performance_packages

- name: create pg_performance installation directory
  file:
    path: "{{ pg_performance_install_dir }}"
    state: directory

- name: install pgperformance.py script
  copy:
    src: pgperformance.py
    dest: "{{ pg_performance_install_dir }}/pgperformance.py"
    mode: 0755

- name: report generation script
  copy:
    content: |
      #!/usr/bin/env bash

      {{ pg_performance_install_dir }}/pgperformance.py \
          | tidy -q \
          > {{ pg_performance_report_dir }}/report-$(date +%Y%m%d-%H%M%S).html
    dest: "{{ pg_performance_install_dir }}/pgperformance_generate_report"
    mode: 0755

- name: generate configuration file
  copy:
    content: "{{ pg_performance_config|to_nice_yaml }}"
    dest: "/etc/pgperformance.yml"
    mode: 0600

- name: report directory
  file:
    dest: "{{ pg_performance_report_dir }}"
    state: directory

- name: cron job for report running
  cron:
    name: generate pgperformance report
    minute: 50
    hour: 23
    job: "{{ pg_performance_install_dir }}/pgperformance_generate_report"

- name: setup nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
