---

- hosts: all
  tasks:
    - name: Add local host for checking purposes
      add_host:
        name: localhost
        hostname: localhost
        ansible_connection: local
        ansible_python_interpreter: python2

- hosts: all
  tasks:
    - name: Write .pgpass
      copy:
        dest: ~/.pgpass
        content: |
          *:*:*:postgres:{{ postgres_passwd }}
        mode: 0600
      become: no
      when: inventory_hostname == 'localhost'

    - name: Shoot master database in the face
      shell:
        /etc/init.d/repmgrd stop
        kill -SEGV $(cat /var/run/postgresql/9.4-main.pid)
      ignore_errors: yes
      become: yes
      when: inventory_hostname == 'db0'

    - name: Waiting for failover to happen
      wait_for:
        timeout: 120
      when: inventory_hostname == 'localhost'

    - name: Check cluster availability
      shell: >
        pgbench -i -s 10 -h {{ hostvars[item].ansible_ssh_host }}
        -p {{ hostvars[item].pgbouncer_listen_port }} -U postgres
      with_items: "{{ groups['lbs'] }}"
      become: no
      when: inventory_hostname == 'localhost'
